### PR TITLE
ENH adding python 2.7

### LINKED ISSUE #37: @conda-forge-admin add python 2.7
Issue:

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

### PR DESCRIPTION
**Pull request by conda-forge-linter**
Hi! This is the friendly automated conda-forge-webservice.

I've added python 2.7 as instructed in #37.

Merge this PR to enable Python 2.7.

**WARNING: Python 2.7 reached end-of-life on 2020-01-01. `conda-forge` provides no support for Python 2.7 builds and all existing builds are provided on an "as-is" basis. Python 2.7 builds on the `win` platform are not possible since we do not build against `vs2008` in our CI providers.**

Here's a checklist to do before merging.
- [ ] Bump the build number if needed.

Fixes #37

### CODE REVIEW

**Comment by beckermr** [comment]
@isuruf What did I do wrong here? The python 2.7 build is not ignored on windows and the rest of the python 3.X builds are gone for linux and osx. Do we need to insert extend_keys somwhere? This would require us to do that in the central pinnings file too.

**Comment by isuruf** [comment]
You need the other versions too. (The way it is right now in CFP package)

**Comment by beckermr** [comment]
Well, that is annoying. Can we add the extend_keys section for python to the CFP package and then add it in the command too or will that cause other issues?

**Comment by isuruf** [comment]
>  Can we add the extend_keys section for python to the CFP package and then add it in the command too or will that cause other issues?

Yes, it'll cause other issues with existing feedstocks extending `python` key.

**Comment by isuruf** [comment]
I mean extending `python` key by explicitly adding all versions

**Comment by beckermr** [comment]
kk. I'm gonna add this to the python 2 deprecation PR and make another PR on web services

**Pull request closed without merging**
