### PR TITLE
MNT: Re-rendered with conda-build 3.21.7, conda-smithy 2.4.0.post.dev…

### PR DESCRIPTION
**Pull request by beckermr**
…2127, and conda-forge-pinning 2021.12.07.13.39.21

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by beckermr** [comment]
Ah I forgot the -c conda-forge.

**Comment by beckermr** [comment]
ok @isuruf, check now. the updates look a lot more sane!

**Comment by isuruf** [comment]
1. why is libmamba getting dowgraded?
2. why is there an upgrade from boa 0.6 -> 0.7 and then 0.7-> 0.8?

cc @wolfv

**Comment by beckermr** [comment]
I have no idea about those questions but I don't see why they are relevant really. The PR on smithy works as advertised and produces on of many correct solutions given the constraints, does it not?

**Comment by beckermr** [comment]
libmamba is version with mamba and so that downgrade is related to the mamba one. 

boa 0.8.0 is pinned at mamba 0.18: https://github.com/conda-forge/boa-feedstock/blob/master/recipe/meta.yaml#L30

**Comment by isuruf** [comment]
The whole point of using mamba is for performance. If by updating like this, we worsen the performance, why bother?

**Comment by beckermr** [comment]
> The whole point of using mamba is for performance. If by updating like this, we worsen the performance, why bother?

Two runs of mamba is still faster than a single run of conda when it has to pull the full repodata and try multiple solves (first on current and then on full repodata).

**Comment by beckermr** [comment]
I can tell by watching it that it is already faster, but I don't have actual numbers.

**Comment by beckermr** [comment]
@conda-forge-admin rerender

**Comment by beckermr** [comment]
Using conda and the latest pinnings we are getting the old version of boa and the solve is taking several minutes:

```

    conda-env-2.6.0            |                1           2 KB  conda-forge
    conda-forge-ci-setup-3.17.1|   py38hcd7a344_1          42 KB  conda-forge
    jq-1.6                     |    h36c2ea0_1000         346 KB  conda-forge
    mamba-0.17.0               |   py38h2aa5da1_0         812 KB  conda-forge
    oniguruma-6.9.7.1          |       h7f98852_0         409 KB  conda-forge
    shyaml-0.6.2               |     pyhd3deb0d_0          21 KB  conda-forge
    watchgod-0.7               |     pyhd8ed1ab_0          14 KB  conda-forge
    ------------------------------------------------------------
                                           Total:         1.8 MB

The following NEW packages will be INSTALLED:

  click              conda-forge/linux-64::click-8.0.3-py38h578d9bd_1
  conda-env          conda-forge/noarch::conda-env-2.6.0-1
  conda-forge-ci-se~ conda-forge/linux-64::conda-forge-ci-setup-3.17.1-py38hcd7a344_1
  jq                 conda-forge/linux-64::jq-1.6-h36c2ea0_1000
  oniguruma          conda-forge/linux-64::oniguruma-6.9.7.1-h7f98852_0
  shyaml             conda-forge/noarch::shyaml-0.6.2-pyhd3deb0d_0
  watchgod           conda-forge/noarch::watchgod-0.7-pyhd8ed1ab_0

The following packages will be UPDATED:

  boa                conda-forge/linux-64::boa-0.6.2-py38h~ --> conda-forge/noarch::boa-0.7.1-pyha770c72_0
  mamba                               0.15.3-py38h2aa5da1_0 --> 0.17.0-py38h2aa5da1_0
```

I don't understand why conda insists on a solution that has two lower version numbers compared to another.

**Comment by beckermr** [comment]
cc @isuruf on the note above

**Comment by beckermr** [comment]
@conda-forge-admin restart ci

**Comment by beckermr** [comment]
ok @isuruf - take a look here

**Pull request closed without merging**
